# Manipulacion de datos con Python 3

In [1]:
import numpy as np

In [4]:
import numpy as np
arreglo = np.array(0, 24, (5,5))
arreglo

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [9]:
matriz = np.reshape(arreglo, (5,5))
matriz

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [10]:
arreglo[7]=1000

In [11]:
arreglo

array([   0.,    1.,    2.,    3.,    4.,    5.,    6., 1000.,    8.,
          9.,   10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,
         18.,   19.,   20.,   21.,   22.,   23.,   24.])

In [12]:
matriz

array([[   0.,    1.,    2.,    3.,    4.],
       [   5.,    6., 1000.,    8.,    9.],
       [  10.,   11.,   12.,   13.,   14.],
       [  15.,   16.,   17.,   18.,   19.],
       [  20.,   21.,   22.,   23.,   24.]])

In [13]:
m1 = matriz[2:4, 1:3]
m1

array([[11., 12.],
       [16., 17.]])

In [14]:
m1[0,0] = 5000
m1

array([[5000.,   12.],
       [  16.,   17.]])

In [15]:
matriz

array([[0.0e+00, 1.0e+00, 2.0e+00, 3.0e+00, 4.0e+00],
       [5.0e+00, 6.0e+00, 1.0e+03, 8.0e+00, 9.0e+00],
       [1.0e+01, 5.0e+03, 1.2e+01, 1.3e+01, 1.4e+01],
       [1.5e+01, 1.6e+01, 1.7e+01, 1.8e+01, 1.9e+01],
       [2.0e+01, 2.1e+01, 2.2e+01, 2.3e+01, 2.4e+01]])

In [16]:
m2 = m1.copy()
m2

array([[5000.,   12.],
       [  16.,   17.]])

In [17]:
m2[0,1]= 8000
m2

array([[5000., 8000.],
       [  16.,   17.]])

In [18]:
matriz

array([[0.0e+00, 1.0e+00, 2.0e+00, 3.0e+00, 4.0e+00],
       [5.0e+00, 6.0e+00, 1.0e+03, 8.0e+00, 9.0e+00],
       [1.0e+01, 5.0e+03, 1.2e+01, 1.3e+01, 1.4e+01],
       [1.5e+01, 1.6e+01, 1.7e+01, 1.8e+01, 1.9e+01],
       [2.0e+01, 2.1e+01, 2.2e+01, 2.3e+01, 2.4e+01]])

In [19]:
lista = [1,2,3,4,5,6,7,8,9,10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
sl = lista[3:6]
sl

[4, 5, 6]

In [21]:
sl[0]= 1000
sl

[1000, 5, 6]

In [22]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]